# Linear Algebra for CpE
## Laboratory 7 : Matrix Operations

Now that you have a fundamental knowledge about representing and operating with vectors as well as the fundamentals of matrices, we'll try to the same operations with matrices and even more.

### Objectives
At the end of this activity you will be able to:
1. Be familiar with the fundamental matrix operations.
2. Apply the operations to solve intemrediate equations.
3. Apply matrix algebra in engineering solutions.

## Activity

### Task 1

Prove and implement the remaining 6 matrix multiplication properties. You may create your own matrices in which their shapes should not be lower than $(3,3)$.
In your methodology, create individual flowcharts for each property and discuss the property you would then present your proofs or validity of your implementation in the results section by comparing your result to present functions from NumPy.

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [ ]:
A = np.array([
    [1, 2, 1],
    [2, 0, 2],
    [2, 1, 1]
])
B = np.array([
    [1,1,2],
    [3,3,1],
    [-1,-2,0]
])
C = np.array([
    [0,1,1],
    [1,1,2],
    [3,3,1]
])
print(A.shape)
print(B.shape)
print(C.shape)


(3, 3)
(3, 3)
(3, 3)


1. $A \cdot B \neq B \cdot A$

In [ ]:
A @ B



array([[ 6,  5,  4],
       [ 0, -2,  4],
       [ 4,  3,  5]])

In [ ]:
B @ A

array([[ 7,  4,  5],
       [11,  7, 10],
       [-5, -2, -5]])

In [ ]:
np.array_equiv(A @ B , B @ A)

False

 2. $A \cdot (B \cdot C) = (A \cdot B) \cdot C$

In [ ]:
A @ (B @ C)

array([[17, 23, 20],
       [10, 10,  0],
       [18, 22, 15]])

In [ ]:
(A @ B) @ C

array([[17, 23, 20],
       [10, 10,  0],
       [18, 22, 15]])

In [ ]:
  np.array_equiv((A @ (B @ C)),((A @ B)@C) )

True

 3. $A\cdot(B+C) = A\cdot B + A\cdot C$

In [ ]:
A @ (B + C)

array([[11, 11, 10],
       [ 6,  6,  8],
       [ 8,  9, 10]])

In [ ]:
A @ B + A @ C


array([[11, 11, 10],
       [ 6,  6,  8],
       [ 8,  9, 10]])

In [ ]:
np.array_equiv(A @ (B + C),A @ B + A @ C )

True

 4. $(B+C)\cdot A = B\cdot A + C\cdot A$

In [ ]:
(B+C) @ A

array([[11,  5,  8],
       [18, 11, 15],
       [ 6,  5,  5]])

In [ ]:
B @ A + C @ A

array([[11,  5,  8],
       [18, 11, 15],
       [ 6,  5,  5]])

In [ ]:
np.array_equiv((B+C) @ A , B @ A + C @ A)

True

 5. $A\cdot I = A$

In [ ]:
I = np.linalg.inv(A)
I

array([[-0.5 , -0.25,  1.  ],
       [ 0.5 , -0.25,  0.  ],
       [ 0.5 ,  0.75, -1.  ]])

In [ ]:
A @ I


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
A

array([[1, 2, 1],
       [2, 0, 2],
       [2, 1, 1]])

In [ ]:
np.allclose(np.dot(A,I), np.eye(3))

True

6. $A\cdot \emptyset = \emptyset$
